export const GIO_WORKFLOW_STAGES = [
  {
    stage_name: "GIO Case Registration",
    stage_order: 1,
    responsible_role: "secretary",
    department: "GIO",
    description: "Secretary registers the GIO case and assigns Chief of GIO",
  },
  {
    stage_name: "Chief of GIO Decision",
    stage_order: 2,
    responsible_role: "chief_of_gio",
    department: "GIO",
    description: "Chief of GIO first review / direction after registration",
  },
  {
    stage_name: "GIO Claim Adjuster Review",
    stage_order: 3,
    responsible_role: "gio_claim_adjuster",
    department: "GIO",
    description: "GIO Claim Adjuster works the case as directed",
  },
  {
    stage_name: "GIO Claim Manager Review",
    stage_order: 4,
    responsible_role: "gio_claim_manager",
    department: "GIO",
    description: "GIO Claim Manager review before Director",
  },
  {
    stage_name: "Director Decision",
    stage_order: 5,
    responsible_role: "director",
    department: "GIO",
    description: "Director decision within delegated authority",
  },
  {
    stage_name: "Chief of GIO Approval",
    stage_order: 6,
    responsible_role: "chief_of_gio",
    department: "GIO",
    description: "Chief of GIO second decision / final approval after Director",
  },
  {
    stage_name: "CEO Decision",
    stage_order: 7,
    responsible_role: "ceo",
    department: "GIO",
    description: "CEO decision when required by amount or case type",
  },
  {
    stage_name: "GIO Case Closure",
    stage_order: 8,
    responsible_role: "secretary",
    department: "GIO",
    description: "Secretary closes the case",
  },
];

export const GIO_CASE_REASONS = [
  "Standard_Claim_Approval",
  "Work_Order_Approval",
  "Additional_WO_Approval",
  "Claim_Within_15_Days_Case",
  "Repair_Approval",
  "Total_Loss_Approval",
  "Additional_Repair_Approval",
  "Payment_Approval",
  "Direct_Cash_Payment_Approval",
  "Vendor_Payment_Approval",
  "Legal_Expense_Approval",
  "Advice_Request",
  "Legal_Advice",
  "Technical_Advice",
  "Third_Party_Recovery_Advice",
  "Cash_Option_Approval",
  "Less_Salvage_Verification",
  "Ex_gratia_Claim_Approval",
  "Customer_Complaint_Handling",
  "Other_Management_Decisions",
];
