export const GIO_WORKFLOW_STAGES = [
  {
    stage_name: "GIO Case Registration",
    stage_order: 1,
    responsible_role: "secretary",
    department: "GIO",
    description: "Secretary registers the GIO case",
  },
  {
    stage_name: "Director Assignment",
    stage_order: 2,
    responsible_role: "director",
    department: "GIO",
    description: "Director assigns GIO Claim Manager",
  },
  {
    stage_name: "Manager Assignment",
    stage_order: 3,
    responsible_role: "gio_claim_manager",
    department: "GIO",
    description: "Manager assigns GIO Claim Principal",
  },
  {
    stage_name: "GIO Case Work",
    stage_order: 4,
    responsible_role: "gio_principal_claim_officer",
    department: "GIO",
    description: "GIO Claim Principal works the case",
  },
  {
    stage_name: "GIO Claim Manager Review",
    stage_order: 5,
    responsible_role: "gio_claim_manager",
    department: "GIO",
    description: "Manager may finalize within authority or forward",
  },
  {
    stage_name: "Director Decision",
    stage_order: 6,
    responsible_role: "director",
    department: "GIO",
    description: "Director may finalize or forward",
  },
  {
    stage_name: "Senior Director Decision",
    stage_order: 7,
    responsible_role: "senior_director",
    department: "GIO",
    description: "Senior Director may finalize or forward",
  },
  {
    stage_name: "Chief of GIO Approval",
    stage_order: 8,
    responsible_role: "chief_of_gio",
    department: "GIO",
    description: "Chief of GIO may finalize or forward",
  },
  {
    stage_name: "CEO Decision",
    stage_order: 9,
    responsible_role: "ceo",
    department: "GIO",
    description: "CEO decision when required",
  },
  {
    stage_name: "GIO Case Closure",
    stage_order: 10,
    responsible_role: "secretary",
    department: "GIO",
    description: "Secretary closes the case",
  },
];

export const GIO_APPROVAL_TIER_STAGES = [
  "GIO Claim Manager Review",
  "Director Decision",
  "Senior Director Decision",
  "Chief of GIO Approval",
  "CEO Decision",
];

export const GIO_CASE_REASONS = [
  "Standard_Claim_Approval",
  "Work_Order_Approval",
  "Additional_WO_Approval",
  "Claim_Within_15_Days_Case",
  "Repair_Approval",
  "Total_Loss_Approval",
  "Additional_Repair_Approval",
  "Payment_Approval",
  "Direct_Cash_Payment_Approval",
  "Vendor_Payment_Approval",
  "Legal_Expense_Approval",
  "Advice_Request",
  "Legal_Advice",
  "Technical_Advice",
  "Third_Party_Recovery_Advice",
  "Cash_Option_Approval",
  "Less_Salvage_Verification",
  "Ex_gratia_Claim_Approval",
  "Customer_Complaint_Handling",
  "Other_Management_Decisions",
];
